"""adding columns to pitches table

Revision ID: 1b03fde075c2
Revises: 5b45f68e98fb
Create Date: 2021-09-19 00:58:05.344791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b03fde075c2'
down_revision = '5b45f68e98fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_title', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_itself', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'pitch_itself')
    op.drop_column('pitches', 'pitch_category')
    op.drop_column('pitches', 'pitch_title')
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###
