"""adding email column to user model

Revision ID: 8beb98f3591d
Revises: 3ac74d503e20
Create Date: 2021-09-18 20:29:46.772280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8beb98f3591d'
down_revision = '3ac74d503e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
