"""adding indexing to username in user class model

Revision ID: 929cdcad3ad0
Revises: 6fc83d4856e1
Create Date: 2021-09-19 12:20:10.239454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929cdcad3ad0'
down_revision = '6fc83d4856e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
